### ISSUE TITLE
Generic icons which aren't an application appearing in dock

### ISSUE THREAD

**Issue by stuartlangridge** [robint99/mate-dock-applet#136] opened 2018-04-28 13:54 UTC
The dock appears to be misidentifying something as an application which isn't there. I currently have two generic "cog" icons and four generic "[?]" icons in my dock, none of which do anything when clicked. I don't know how to identify what mate-dock-applet thinks they are; I'd be happy to provide extra data if I'm told how.

![image](https://user-images.githubusercontent.com/4356350/39397248-11085a54-4af4-11e8-8afc-74e11ae8136d.png)

**Comment by robint99** [comment] 2018-05-06 08:27
I've been trying to reproduce this issue but without success. I've duplicated your panel layout and even installed and played about with Vistual Studio and Chromium, all to no avail. I've a couple of questions: 

Is there anything specific that causes these spurious icons to appear or do they just seem to randomly turn up out of nowhere? 

To help me duplicate your setupCould you send me your dock configuration (i.e. your ~/.config/mate_dock_applet.conf file)?. Also, if you're using a custom panel layout could I have that too - it'll be in /usr/share/mate-panel/layouts.

Thanks,

Robin

**Comment by stuartlangridge** [comment] 2018-05-06 16:54
To keep you in the loop, I _think_ this might be something to do with incorrectly unmounted devices, which aren't being cleared up (and also show up in Mate's Caja file manager, in the Computer section; I have about thirty drives showing up there, which aren't plugged in any more; they've been removed, but something isn't removing those entries from Caja or some lower-level layer). So if that's fixed, this may stop the bad launcher icons from appearing. However, I think it might be worth working on this anyway; I honestly can't think of a reason why mate-dock-applet should show an icon with no quick menu, no name, and no click action, so having the dock ignore these things even if it's _truly_ a bug in some underlying layer might be a good idea. 

dock config:

```
<?xml version='1.0' encoding='us-ascii'?>
<root><pinned_apps><desktop_file name="firefox.desktop" /><desktop_file name="matecc.desktop" /><desktop_file name="chromium-browser.desktop" /><desktop_file name="telegramdesktop.desktop" /><desktop_file name="caja.desktop" /><desktop_file name="code.desktop" /><desktop_file name="slack_slack.desktop" /><desktop_file name="sublime_text.desktop" /></pinned_apps><ind_type light="6" /><show_all show_all="True" /><multi_ind show_multi="True" /><use_win_list uwl="True" /><win_from_cur_ws_only wcw="False" /><panel_change_color pcc="False" /><dock_panel_change_only dcc="False" /><panel_act_list pal="True" /><bg_type type="1" /><fallback_bar_col><col value="128" /><col value="128" /><col value="128" /></fallback_bar_col><spacing spc="4" /><attention_type type="1" /><popup_delay delay="1000" /><saved_configs /><pinned_apps_all_workspaces paoaws="True" /><dock_fixed_size dfs="-1" /></root>
```

I'm using Ubuntu MATE's "Mutiny" layout, not a custom one. (I was using a custom layout when I filed this bug, but I've reverted to Mutiny to see if it fixed the problem, which it didn't :))

**Comment by robint99** [comment] 2018-05-08 06:56
Caja seems to be working fine for me. I don't have thirty spare drives to connect :) but plugging and unplugging various USB sticks caused no problems for me.

However, I think @shiarus is probably right and the icons that kept appearing in the dock were there because the 'skip-tasklist' flag wasn't being honoured by the applet. I've just committed a fix for that and I'm hopeful it'll sort out this issue as well. If you want to give it a try you'll have to compile and install the latest version of the applet from source - instructions are on the main page, but if you get stuck just let me know...

Robin

**Comment by shiarus** [comment] 2018-05-20 07:18
I would love to compile from source to test, but you did not release this fix yet.  Your latest version release is V0.85 released on March 20th, before my bug report.  :)

**Comment by robint99** [comment] 2018-05-21 09:34
You can always git clone the latest source and compile that, but if you
don't want to do that then just hang on for another week or two. I'm slowly
working my way through the bugs reported since 18.04 was released, and once
I've got another one or two out of the way I'll release a new version of
the applet then. :)

**Comment by kowach** [comment] 2018-09-12 07:39
I have similar problem after upgrading to 18.04 and activating dock applet. Those cogs are spawning from nowhere. 

 ![selection_059](https://user-images.githubusercontent.com/733128/45409118-9b1fa400-b66e-11e8-969a-b9c8a4b463a6.png)

mate-dock-applet/bionic,now 0.85-1 amd64 [installed]

mate_dock_applet.conf

    <?xml version='1.0' encoding='us-ascii'?>
    <root><pinned_apps><desktop_file name="caja-browser.desktop" /><desktop_file name="org.kde.krusader.desktop" /><desktop_file name="mate-tweak.desktop" /><desktop_file name="matecc.desktop" /><desktop_file name="mate-calc.desktop" /><desktop_file name="mate-terminal.desktop" /><desktop_file name="putty.desktop" /><desktop_file name="google-chrome.desktop" /><desktop_file name="firefox.desktop" /><desktop_file name="chrome-pjkljhegncpnkpknbcohdijeoejaedia-Default.desktop" /><desktop_file name="com.teamviewer.TeamViewer.desktop" /><desktop_file name="jetbrains-phpstorm.desktop" /></pinned_apps><ind_type light="6" /><show_all show_all="True" /><multi_ind show_multi="True" /><use_win_list uwl="True" /><win_from_cur_ws_only wcw="False" /><panel_change_color pcc="False" /><dock_panel_change_only dcc="False" /><panel_act_list pal="True" /><bg_type type="1" /><fallback_bar_col><col value="128" /><col value="128" /><col value="128" /></fallback_bar_col><spacing spc="5" /><attention_type type="1" /><popup_delay delay="1000" /><saved_configs /><pinned_apps_all_workspaces paoaws="True" /><dock_fixed_size dfs="-1" /></root>

**Comment by robint99** [comment] 2018-09-12 08:27
While fixing issue #139 I was able to reproduce the cog icon problem, and the fix for #139 also prevents cog icons appearing for me. It may solve your problem too. If you want to get try it for yourself you'll have to install the latest version of the applet. There are two ways to do this:

* manually compile the latest code from gihub using the instructions in README.md
* download and run a Python script I've written to do all of the hard work for you and install the latest development version of the applet. You can find it [here](https://github.com/robint99/misc) in one of my other repositories.

Hopefully this will get rid of the cogs for you :)

**Comment by kowach** [comment] 2018-09-12 11:08
Great :+1: thx.

But I'll wait for apt update :)

**Comment by itcrowd72** [comment] 2018-11-08 06:54
I confirm this bug in Ubuntu 18.04 MATE

![screenshot at 2018-11-08 11-53-31](https://user-images.githubusercontent.com/29428813/48182454-02936080-e34d-11e8-9c0b-5b9b3ff63738.png)

**Comment by itcrowd72** [comment] 2018-11-08 07:51
I install 0.87 package and will be test it

**Closed** 2019-01-24 06:59 UTC

**Comment by itcrowd72** [comment] 2019-01-24 07:10
I confirm, this package works great
