### ISSUE TITLE
Unable to restore minimized windows

### ISSUE THREAD

**Issue by rcearfoss** [robint99/mate-dock-applet#146] opened 2018-05-17 18:42 UTC
Having an issue where I am sometimes unable to restore minimized windows. journalctrl shows the following error when I minimize a window that I believe is related:
python3[1827]: Received a timestamp of 0; window activation may not function properly.

I can alt+tab to restore the window but I cannot just click the windows icon in Mate-Dock to restore it. Using Mates Windows list I do not have any problem minimizing and restoring windows it just seems to happen when using Mate-Dock. Any Suggestions?

**Comment by robint99** [comment] 2018-05-24 07:45
It seems to be working fine for me. Could you let me know which version of the applet and which distro you're using?

Thanks.

**Comment by rcearfoss** [comment] 2018-05-24 19:06
I am trying to determine the version of Mate-Dock but not having much luck. It was pre-installed on the latest Ubuntu Mate, But I have also had the same issue on Antegros with Mate.

**Comment by rcearfoss** [comment] 2018-05-25 10:55
I just updated mate dock and I don't think I am having the issue anymore. I still see the python3[1827]: Received a timestamp of 0; window activation may not function properly message but I can still restore windows.

**Comment by rcearfoss** [comment] 2018-05-29 11:57
nevermind, same problem.

**Comment by robint99** [comment] 2018-06-05 07:20
Are there any apps in particular which show this problem or does it appear to affect all of them?

**Comment by rcearfoss** [comment] 2018-06-07 12:36
It does seem to happen with KeepassXC and Caja most frequently.

**Comment by edwin-v** [comment] 2018-06-21 22:44
I'm having a problem that might just be this one. Steps to reproduce

- Open a terminal window.
- Open a second terminal window.
- Minimize one of the windows.
- Close the other window.
- Now the dock be able to raise the remaining terminal.

Instead of minimizing, you can also select a window from another program before closing one window.
Also works with Caja (and probably others).

Completely reproducible on 0.85 from Ubuntu MATE.

**Comment by elcste** [comment] 2018-06-27 01:13
I've been having the same problem and not quite finding the sequence, but @edwin-v has it: minimize one window, then close the other. Now you can't reopen the minimized one. The app doesn't seem to matter. I just tried Firefox in addition to MATE Terminal and Caja.

I'm using 0.86 built from source on Ubuntu MATE 18.04.

**Comment by robint99** [comment] 2018-06-29 06:55
I've just committed a fix for this issue. Thanks very much for the info on reproducing the bug!

**Closed by robint99** 2018-06-29 06:55 UTC

**Comment by elcste** [comment] 2018-06-29 12:04
Yes, seems fixed to me.
