### ISSUE TITLE
[Linux Mint 18 | MATE 1.14] Dock applet broken with Compiz

### ISSUE THREAD

**Issue by NoXPhasma** [robint99/mate-dock-applet#60] opened 2016-07-05 21:46 UTC
I recently switched to Linux Mint 18, which comes with Mate 1.14. When I use Compiz as Window Manager, as I do all the time, the dock applet gets crazy when I use 2 Docks or just doesn't work as expected with one dock.

Two Panels, two docks:
I have 2 panels and every one has one dock. Instead of switching to a window when I click on a icon, the icon just starts to blinking and doesn't bring up the window. When I click another icon that also starts blinking. Sometimes I can switch to another window.

Two panels, one Dock:
When I delete one dock and only use one it just doesn't always bring up the window I click on. In some cases it works when I go through the open windows and back on that which doesn't work.

This is not related to the previous bug #3, since I don't use "Keep previews of minimized windows". I've already disabled all plugins beside OpenGL, Composite and Window decorations, without success.

When I switch back to Marco the dock works perfectly fine.

Linux Mint 16 x64
mate-dock-applet: 0.71 & 0.72
mate-panel: 1.14.0 (GTK2)
compiz: 0.9.12.2

**Comment by kajzersoze** [comment] 2016-07-26 22:38
I can confirm this issue, tried with just one dock and two panels.
Actually I'm glad I found this report because I would have never figured out that it was compiz causing it. As soon as I switched to marco everything was fine.

Gentoo x64
mate-dock-applet : git 
mate : 1.15.1
compiz-reloaded

**Comment by kajzersoze** [comment] 2016-07-28 22:17
Found the problem !
In CCSM -> General Options -> Focus & Raise Behaviour , Focus Prevention Level has to be set to Off

**Comment by NoXPhasma** [comment] 2016-07-29 11:15
Good find! This solves it for me too.

**Comment by kajzersoze** [comment] 2016-07-29 18:05
Yeah, after 24hrs there are no issues whatsoever, you can close this issue.

**Comment by NoXPhasma** [comment] 2016-07-29 18:12
I don't think it should be closed. The steal prevention isn't there for no reason. The applet should work with it enabled. Let's see what @robint99 has to say about it.

**Comment by kajzersoze** [comment] 2016-07-29 19:10
True, if window list applet can work with it enabled then I guess this one should work too.

**Comment by robint99** [comment] 2016-07-31 09:01
I don't know much about Compiz but am currently installing Mint in a virtual machine and will have a look at this is in a day or two.

**Comment by robint99** [comment] 2016-08-01 08:40
I was able to reproduce the problems with the default Focus Prevention setting of Low, and after setting it to off the applet worked as normal. Everything also works when using Marco or Compton as the window manager.

So I think the problem lies somewhere with Compiz and the focus prevention setting. Historically its been the cause of problems in Unity (e.g. see [here](http://www.webupd8.org/2015/11/fix-for-some-apps-starting-behind.html) and [here](https://bugs.launchpad.net/linuxmint/+bug/1542618)) and in fact Ubuntu Mate 16.04 ships with it set to Off by default. I wonder if there is a reason for this...

Given all this I think its best just close this issue and consider it a strange thing that happens with Compiz. I will put a note in the README  to say that Compiz users should set Focus Prevention Level to Off though.

Feel free to discuss further if you disagree...

**Closed by robint99** 2016-08-01 08:40 UTC

**Comment by hugonz** [comment] 2018-11-12 17:05
The Focus Prevention off setting fixed my problem: when I tried to switch to an open window from mate-dock-applet, the applet icon would only blink if there was a maximized window and I'd have to use the window switcher.
