### ISSUE TITLE
Is mate-dock-applet compatible with MATE 1.8?

### ISSUE THREAD

**Issue by spvkgn** [robint99/mate-dock-applet#81] opened 2016-10-30 15:27 UTC
I tried to add v0.75 to panel but nothing happens after adding it in "Add to panel" window.
I'm on Ubuntu 12.04 with MATE 1.8.2, python 3.2.3.

![-](https://cloud.githubusercontent.com/assets/4147135/19837588/11aee8fc-9ee7-11e6-93e4-63322288a8ab.png)

**Comment by robint99** [comment] 2016-11-02 09:42
I've never actually tried to run the applet on Ubuntu 12.04 (the earliest
I've tried is 14.04) so I'm not sure what's gone wrong.

To help find out what the problem is you can open a terminal and run this
command:

python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py

Then try adding the applet to a panel and see what output appears in the
terminal.

Cheers,

**Comment by spvkgn** [comment] 2016-11-02 10:24
With steps you described I'm getting this error:

~ $ python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py                                                                           /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:47: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 461, in applet_factory
    applet_fill(applet)
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 409, in applet_fill
    the_dock = dock.Dock(applet)
  File "/usr/lib/mate-applets/mate-dock-applet/dock.py", line 346, in __init__
    self.app_win_list = dock_win_list.DockWinList(self.wnck_screen)
  File "/usr/lib/mate-applets/mate-dock-applet/dock_win_list.py", line 174, in __init__
    self.__tree_view.set_row_separator_func(self.check_sep)
  File "/usr/lib/python3/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
TypeError: set_row_separator_func() takes exactly 3 arguments (2 given)

**Comment by robint99** [comment] 2016-11-03 07:57
It looks as though 12.04 uses some older libraries that are not compatible with 14.04 and up. To be honest, I don't think its worth trying to get the applet to work with this old code. I don't know exactly how much work is going to be involved - the TypeError above could just be the tip of the iceberg. Also, 12.04 is going to reach end of life in a few months anyway, so it would be something of a wasted effort...

So I think the best thing to do is to close this issue and mark the applet as not compatible with 12.04. I realise this doesn't help you at all. Apologies for that. All I can do is suggest that when you upgrade from 12.04 you try the applet again. If you upgrade to 14.04 you'll need to compile from source, but if you go to 16.04, the applet is in the official repos....

Sorry I couldn't be more helpful :(

**Closed by robint99** 2016-11-03 07:57 UTC
