### ISSUE TITLE
Can't reorder pinned dock items

### ISSUE THREAD

**Issue by stuartlangridge** [robint99/mate-dock-applet#138] opened 2018-04-28 19:18 UTC
In v0.85, there doesn't seem to be a way to re-order pinned items in the dock; dragging items doesn't work, and the right-click menu doesn't have move-up and move-down items any more?

**Comment by gabdub** [comment] 2018-04-28 21:29
There is an issue with dragging (see issue #132) that can be related to this.
I managed to reorder some items by dragging, though. Try dragging the item outside the panel before moving it to another position.

**Comment by stuartlangridge** [comment] 2018-04-29 01:42
I've had no luck with dragging items, either by dragging them directly up or down, or by dragging them out of the dock and back in again, with any mouse button :(

**Comment by robint99** [comment] 2018-05-04 10:58
Drag and drop has always been a bit finicky but it worked most of the time. While looking into this issue I was able to identify the cause of the problem. It seems that once the applet's right click menu was shown it wouldn't receive begin drag events from Gtk unless the applet was left clicked again.

Don't know why this should happen but I've reworked the way the icon dragging is initiated so that the applet does it itself rather than relying on Gtk to tell it when to start . It now works reliably all the time. Changes have already been committed and will find their way into the next version of the applet...

**Closed by robint99** 2018-05-04 10:58 UTC
