### ISSUE TITLE
Crashes if setting the pannel to auto hide

### ISSUE THREAD

**Issue by oz123** [robint99/mate-dock-applet#63] opened 2016-07-21 19:20 UTC
```
$ /usr/bin/python /usr/lib/mate-applets/mate-dock-applet/dock_applet.py 

** (dock_applet.py:25933): WARNING **: Failed to get pattern 14874428,0,454

(dock_applet.py:25933): Gdk-ERROR **: The program 'dock_applet.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadPixmap (invalid Pixmap parameter)'.
  (Details: serial 1343 error_code 4 request_code 54 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap
```

**Comment by robint99** [comment] 2016-07-22 06:49
Hi,

I've been trying to reproduce this but haven't had any success. I've tried GTK2 and 3 versions of the applet on Ubuntu Mate and Arch and don't get the error.  

If you can you let me know what version of the applet, what distro you're using and what, if anything, causes the error (e.g. launching an app, panel hiding/unhiding) it would be a great help :)

Thanks

**Comment by oz123** [comment] 2016-07-22 07:24
For some reason, I also can't reproduce it now.

**Comment by oz123** [comment] 2016-07-22 08:13
I managed to recreate the bug. You need to set the panel to autohide, unmark expand, and finally I set the background color of the panel to be transparent. This will crash applet.

**Comment by robint99** [comment] 2016-07-23 06:40
I've tried this again and still can't reproduce the error on either Ubuntu or Arch. So I'm now in the process of installing Gentoo into a virtual machine. I'm not familiar with Gentoo so it may be a few days for me to get it up and running, but as soon as it is I'll investigate this problem.

Incidentally, are you using Gtk2 or Gtk3 MATE desktop?

**Comment by oz123** [comment] 2016-07-23 07:08
I'm using GTK 3.

**Comment by robint99** [comment] 2016-07-27 07:47
I've managed to get Gentoo running on a virtual machine and I've installed Mate and the dock applet from your overlays. I've been able to reproduce the problem you noticed, but I don't think its anything to do with the applet for a couple of reasons.

For one thing, the applet doesn't do anything differently if the panel is hidden. not expanded, or fully transparent - it runs exactly the same code in exactly the same way. For another, it seems that most applets will also crash on these sorts of panels - e.g. I experienced crashes with fish, system monitor, trash, window selector, workspace switcher, and eyes.

I would guess that the problem might be something to do with the way that the overlay compiles MATE (some combination of compiler flags perhaps?) or perhaps related to xorg v1.18 (both Ubuntu and Arch where applets work fine are using 1.17). But either way, I'll close this issue as the problem is not with the dock applet itself...

Cheers,

**Closed by robint99** 2016-07-27 07:47 UTC
