### ISSUE TITLE
MATE Dock Applet mistakes software

### ISSUE THREAD

**Issue by terzag** [robint99/mate-dock-applet#84] opened 2017-03-09 19:10 UTC
Using MATE Dock Applet 0.76 (from WebUpd8's repo) on Ubuntu MATE 16.10 (MATE desktop 1.16).

For some reason, MDA mixes recognition of some running softwares: when I run Gnome-Twitch, it shows the icon for the Itch app. I assume that it's because gnome-twitch has "itch" in its name and MDA uses some kind of regexp to check if apps are running.

**Comment by oscardssmith** [comment] 2018-01-18 04:49
This has allegedly been fixed by now, (at least in Master), so this should probably be closed.

**Comment by terzag** [comment] 2018-01-25 19:21
In which version exactly? From what I see, the last one seems to be 0.80 or am I mistaken? WebUpd8's PPA has 0.80 from november but the issue is still there with it, so not sure if I'm confused by the versions or if it's not (completely) fixed.

**Comment by oscardssmith** [comment] 2018-01-25 19:34
According to https://github.com/robint99/mate-dock-applet/issues/117, which was a dupe of your issue, it's closed, I think.

**Comment by terzag** [comment] 2018-01-25 20:01
Ok. Well, I've tried to compile it but it doesn't launch at all. Not sure if something went wrong during compilation. Guess I'll wait for a prebuilt version (in WebUpd8's PPA or other).

**Comment by robint99** [comment] 2018-01-28 09:18
The bamf stuff isn't in a released version of the applet yet. I'm working on some more big changes and I want to release these and bamf together. It shouldn't be too long to wait, hopefully a couple of weeks at most.

To get you up and running, If you're still using Ubuntu make sure that you have bamfdaemon and libbamf3-2 installed. If that doesn't help, trying running this command

`python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py ` 

in a terminal, then add a dock to a panel and see output you get...

**Comment by terzag** [comment] 2018-01-28 10:06
Both packages are installed but it looks like it's not running or not started by Mate Dock Applet, as I get the following as soon as I run your command, without even needing to add a dock:

Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 67, in <module>
    import docked_app
  File "/usr/lib/mate-applets/mate-dock-applet/docked_app.py", line 60, in <module>
    gi.require_version("Bamf", "3")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Bamf not available

Do I have to manually start bamfdaemon? If so, how?

**Comment by robint99** [comment] 2018-01-28 12:20
Got it, installing package gir1.2-bamf-3 should do the trick.

**Comment by terzag** [comment] 2018-01-28 12:37
It does. :)

And I can confirm that the issue I had with GNOME-Twitch is fixed, it now shows the right icon.

**Comment by robint99** [comment] 2018-01-28 15:13
Ok, glad that's all sorted now :) Will close this issue down.

**Closed by robint99** 2018-01-28 15:13 UTC
